### ISSUE TITLE
Remove target subdirectory

### ISSUE THREAD

**Issue by shinabro** [crotert/SE452Project#2]
add target in the .gitignore file so that the target subdirectory is not checked in

to remove the subdirectory from git, try following commands

1. - git rm -r target (where target is the subdirectory)
2. - git commit -m "Remove build directory"
3. - git push origin master

**Comment by crotert** [comment]
I have added a .gitignore file to ignore the target directory upon code check-in and removed the target directory as suggested.  Thanks for the feedback in setting the github repo up correctly.
